language: cpp
os: osx
compiler:
    - gcc
    - clang

osx_image: xcode7.4
before_install:
- brew install qt5
- brew link qt5 --force
    
script:
- qmake -spec macx-xcode bulkClub.pro
- xcodebuild -list -project bulkClub.xcodeproj
- xcodebuild -scheme bulkClub build
  
